server:
  port: 8000 # 端口
spring:
  application:
    name: consumer-server # 应用名称，会在Eureka中显示

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: true # 是否拉取其它服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://localhost:8761/eureka